trigger:
  batch: true
  branches:
    include:
    - master

pr:
  - master

jobs:
- job: test
  displayName: test job
  steps:
  - checkout: self
    fetchDepth: 1

  - task: PowerShell@2
    displayName: '📦 Test step'
    inputs:
      targetType: 'inline'
      script: |
        echo 'hello from test step'

  - task: jlin-test-task